# docker-compose.yml

version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      # Teruskan semua variabel environment Anda ke kontainer
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=http://localhost:3000
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - NODE_ENV=production
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
    # Shared memory yang lebih besar untuk Chrome
    shm_size: '2gb'
    # Memory limit untuk mencegah crash
    mem_limit: 2g
    # CPU limit yang reasonable
    cpus: '1.0'