# docker-compose.yml

version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      # Teruskan semua variabel environment Anda ke kontainer
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=http://localhost:3000
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      # Flag ini sering membantu file watching di dalam Docker
      - CHOKIDAR_USEPOLLING=true
    volumes:
      # Sinkronkan kode sumber Anda, tetapi abaikan node_modules dan .next
      - .:/app
      - /app/node_modules
      - /app/.next